In [21]:
import pandas as pd
import re
from sklearn import linear_model
from sklearn.preprocessing import PolynomialFeatures
from sklearn import linear_model
from sklearn.model_selection import cross_val_score
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
from sklearn.metrics import mean_squared_error

In [ ]:
data = pd.read_csv("../data/ml_gw_car_insurance.csv")
data.info()

## Max Torque and Max Power (Only Numbers)

In [2]:
data["max_torque"].unique()

array(['60Nm@3500rpm', '113Nm@4400rpm', '91Nm@4250rpm', '250Nm@2750rpm',
       '200Nm@3000rpm', '82.1Nm@3400rpm', '200Nm@1750rpm', '85Nm@3000rpm',
       '170Nm@4000rpm'], dtype=object)

In [3]:
data['torque_Nm'] = data['max_torque'].str.extract('(\d+)').astype(float)
data['torque_rpm'] = data['max_torque'].str.extract('@(\d+)').astype(float)

data[["max_torque", "torque_Nm", "torque_rpm"]]

          max_torque  torque_Nm  torque_rpm
0       60Nm@3500rpm       60.0      3500.0
1       60Nm@3500rpm       60.0      3500.0
2       60Nm@3500rpm       60.0      3500.0
3      113Nm@4400rpm      113.0      4400.0
4       91Nm@4250rpm       91.0      4250.0
...              ...        ...         ...
97650  113Nm@4400rpm      113.0      4400.0
97651  250Nm@2750rpm      250.0      2750.0
97652  113Nm@4400rpm      113.0      4400.0
97653  113Nm@4400rpm      113.0      4400.0
97654  250Nm@2750rpm      250.0      2750.0

[97655 rows x 3 columns]

In [4]:
data["max_power"].unique()

array(['40.36bhp@6000rpm', '88.50bhp@6000rpm', '67.06bhp@5500rpm',
       '113.45bhp@4000rpm', '88.77bhp@4000rpm', '55.92bhp@5300rpm',
       '97.89bhp@3600rpm', '61.68bhp@6000rpm', '118.36bhp@5500rpm'],
      dtype=object)

In [5]:
data['power_bhp'] = data['max_power'].str.extract('(\d+.\d+)').astype(float)
data['power_rpm'] = data['max_power'].str.extract('@(\d+)').astype(float)

data[["max_power", "power_bhp", "power_rpm"]]

               max_power  power_bhp  power_rpm
0       40.36bhp@6000rpm      40.36     6000.0
1       40.36bhp@6000rpm      40.36     6000.0
2       40.36bhp@6000rpm      40.36     6000.0
3       88.50bhp@6000rpm      88.50     6000.0
4       67.06bhp@5500rpm      67.06     5500.0
...                  ...        ...        ...
97650   88.50bhp@6000rpm      88.50     6000.0
97651  113.45bhp@4000rpm     113.45     4000.0
97652   88.50bhp@6000rpm      88.50     6000.0
97653   88.50bhp@6000rpm      88.50     6000.0
97654  113.45bhp@4000rpm     113.45     4000.0

[97655 rows x 3 columns]

## Max Torque and Max Power (Dummies)

In [6]:
#Max Torque Dummies
torque_dummies = pd.get_dummies(data['max_torque'], prefix='torque')
data = pd.concat([data, torque_dummies], axis=1)

data.head()

,Unnamed: 0,policy_id,policy_tenure,age_of_car,age_of_policyholder,area_cluster,population_density,make,segment,model,...,power_rpm,torque_113Nm@4400rpm,torque_170Nm@4000rpm,torque_200Nm@1750rpm,torque_200Nm@3000rpm,torque_250Nm@2750rpm,torque_60Nm@3500rpm,torque_82.1Nm@3400rpm,torque_85Nm@3000rpm,torque_91Nm@4250rpm
0,0,ID00001,0.515874,0.05,0.644231,C1,4990,1,A,M1,...,6000.0,0,0,0,0,0,1,0,0,0
1,1,ID00002,0.672619,0.02,0.375000,C2,27003,1,A,M1,...,6000.0,0,0,0,0,0,1,0,0,0
2,2,ID00003,0.841110,0.02,0.384615,C3,4076,1,A,M1,...,6000.0,0,0,0,0,0,1,0,0,0
3,3,ID00004,0.900277,0.11,0.432692,C4,21622,1,C1,M2,...,6000.0,1,0,0,0,0,0,0,0,0
4,4,ID00005,0.596403,0.11,0.634615,C5,34738,2,A,M3,...,5500.0,0,0,0,0,0,0,0,0,1

In [7]:
#Max Power Dummies
power_dummies = pd.get_dummies(data['max_power'], prefix='power')
data = pd.concat([data, power_dummies], axis=1)

data.head()

,Unnamed: 0,policy_id,policy_tenure,age_of_car,age_of_policyholder,area_cluster,population_density,make,segment,model,...,torque_91Nm@4250rpm,power_113.45bhp@4000rpm,power_118.36bhp@5500rpm,power_40.36bhp@6000rpm,power_55.92bhp@5300rpm,power_61.68bhp@6000rpm,power_67.06bhp@5500rpm,power_88.50bhp@6000rpm,power_88.77bhp@4000rpm,power_97.89bhp@3600rpm
0,0,ID00001,0.515874,0.05,0.644231,C1,4990,1,A,M1,...,0,0,0,1,0,0,0,0,0,0
1,1,ID00002,0.672619,0.02,0.375000,C2,27003,1,A,M1,...,0,0,0,1,0,0,0,0,0,0
2,2,ID00003,0.841110,0.02,0.384615,C3,4076,1,A,M1,...,0,0,0,1,0,0,0,0,0,0
3,3,ID00004,0.900277,0.11,0.432692,C4,21622,1,C1,M2,...,0,0,0,0,0,0,0,1,0,0
4,4,ID00005,0.596403,0.11,0.634615,C5,34738,2,A,M3,...,1,0,0,0,0,0,1,0,0,0

## Binary varianbles for Yes and No Variables

In [8]:
columns = ['is_esc', 'is_adjustable_steering', 'is_tpms', 'is_parking_sensors', 'is_parking_camera','is_front_fog_lights','is_rear_window_wiper','is_rear_window_washer','is_rear_window_defogger','is_brake_assist','is_power_door_locks','is_central_locking','is_power_steering','is_driver_seat_height_adjustable','is_day_night_rear_view_mirror','is_ecw','is_speed_alert']
for col in columns:
    data[col] = data[col].map({'Yes': 1, 'No': 0})

data[['is_esc', 'is_adjustable_steering', 'is_tpms', 'is_parking_sensors', 'is_parking_camera','is_front_fog_lights','is_rear_window_wiper','is_rear_window_washer','is_rear_window_defogger','is_brake_assist','is_power_door_locks','is_central_locking','is_power_steering','is_driver_seat_height_adjustable','is_day_night_rear_view_mirror','is_ecw','is_speed_alert']]

,is_esc,is_adjustable_steering,is_tpms,is_parking_sensors,is_parking_camera,is_front_fog_lights,is_rear_window_wiper,is_rear_window_washer,is_rear_window_defogger,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert
0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1
1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1
2,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1
3,1,1,0,1,1,1,0,0,1,1,1,1,1,1,1,1,1
4,0,0,0,0,1,0,0,0,0,0,1,1,1,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97650,0,1,0,1,0,1,0,0,0,1,1,1,1,1,1,1,1
97651,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1
97652,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1
97653,1,1,0,1,1,1,0,0,1,1,1,1,1,1,1,1,1
97654,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1

## Dummies for Fuel Type, Rear Brakes Type and Transmission Type

In [17]:
#Fuel Type
fuel_type_dummies = pd.get_dummies(data['fuel_type'], prefix='fuel_type')
data = pd.concat([data, fuel_type_dummies], axis=1)


#Rear Brakes
rear_brakes_dummies = pd.get_dummies(data['rear_brakes_type'], prefix='rear_brakes')
data = pd.concat([data, rear_brakes_dummies], axis=1)


#Transmission Type
transmission_type_dummies = pd.get_dummies(data['transmission_type'], prefix='transmission_type')
data = pd.concat([data, transmission_type_dummies], axis=1)

#Segment
segment_dummies = pd.get_dummies(data['segment'], prefix='segment')
data = pd.concat([data, segment_dummies], axis=1)

# steering_type
steering_type_dummies = pd.get_dummies(data['steering_type'], prefix='steering_type')
data = pd.concat([data, steering_type_dummies], axis=1)

data.head()

,Unnamed: 0,policy_id,policy_tenure,age_of_car,age_of_policyholder,area_cluster,population_density,make,segment,model,...,transmission_type_Manual,segment_A,segment_B1,segment_B2,segment_C1,segment_C2,segment_Utility,steering_type_Electric,steering_type_Manual,steering_type_Power
0,0,ID00001,0.515874,0.05,0.644231,1,4990,1,A,1,...,1,1,0,0,0,0,0,0,0,1
1,1,ID00002,0.672619,0.02,0.375000,2,27003,1,A,1,...,1,1,0,0,0,0,0,0,0,1
2,2,ID00003,0.841110,0.02,0.384615,3,4076,1,A,1,...,1,1,0,0,0,0,0,0,0,1
3,3,ID00004,0.900277,0.11,0.432692,4,21622,1,C1,2,...,0,0,0,0,1,0,0,1,0,0
4,4,ID00005,0.596403,0.11,0.634615,5,34738,2,A,3,...,0,1,0,0,0,0,0,1,0,0

In [10]:

# Define regular expression pattern to match only digits
pattern = r'\d+'

# Apply regular expression to 'cluster' column and save as new column
data['area_cluster'] = data['area_cluster'].apply(lambda x: re.search(pattern, x).group())
data['model'] = data['model'].apply(lambda x: re.search(pattern, x).group())

data.head()

,Unnamed: 0,policy_id,policy_tenure,age_of_car,age_of_policyholder,area_cluster,population_density,make,segment,model,...,rear_brakes_Disc,rear_brakes_Drum,transmission_type_Automatic,transmission_type_Manual,segment_A,segment_B1,segment_B2,segment_C1,segment_C2,segment_Utility
0,0,ID00001,0.515874,0.05,0.644231,1,4990,1,A,1,...,0,1,0,1,1,0,0,0,0,0
1,1,ID00002,0.672619,0.02,0.375000,2,27003,1,A,1,...,0,1,0,1,1,0,0,0,0,0
2,2,ID00003,0.841110,0.02,0.384615,3,4076,1,A,1,...,0,1,0,1,1,0,0,0,0,0
3,3,ID00004,0.900277,0.11,0.432692,4,21622,1,C1,2,...,0,1,1,0,0,0,0,1,0,0
4,4,ID00005,0.596403,0.11,0.634615,5,34738,2,A,3,...,0,1,1,0,1,0,0,0,0,0

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97655 entries, 0 to 97654
Data columns (total 96 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Unnamed: 0                        97655 non-null  int64
 1   policy_id                         97655 non-null  object
 2   policy_tenure                     97655 non-null  float64
 3   age_of_car                        97655 non-null  float64
 4   age_of_policyholder               97655 non-null  float64
 5   area_cluster                      97655 non-null  object
 6   population_density                97655 non-null  int64
 7   make                              97655 non-null  int64
 8   segment                           97655 non-null  object
 9   model                             97655 non-null  object
 10  fuel_type                         97655 non-null  object
 11  max_torque                        97655 non-null  object
 12  max_power                         97655 non-null  object
 13  engine_type                       97655 non-null  object
 14  airbags                           97655 non-null  int64
 15  is_esc                            97655 non-null  int64
 16  is_adjustable_steering            97655 non-null  int64
 17  is_tpms                           97655 non-null  int64
 18  is_parking_sensors                97655 non-null  int64
 19  is_parking_camera                 97655 non-null  int64
 20  rear_brakes_type                  97655 non-null  object
 21  displacement                      97655 non-null  int64
 22  cylinder                          97655 non-null  int64
 23  transmission_type                 97655 non-null  object
 24  gear_box                          97655 non-null  int64
 25  steering_type                     97655 non-null  object
 26  turning_radius                    97655 non-null  float64
 27  length                            97655 non-null  int64
 28  width                             97655 non-null  int64
 29  height                            97655 non-null  int64
 30  gross_weight                      97655 non-null  int64
 31  is_front_fog_lights               97655 non-null  int64
 32  is_rear_window_wiper              97655 non-null  int64
 33  is_rear_window_washer             97655 non-null  int64
 34  is_rear_window_defogger           97655 non-null  int64
 35  is_brake_assist                   97655 non-null  int64
 36  is_power_door_locks               97655 non-null  int64
 37  is_central_locking                97655 non-null  int64
 38  is_power_steering                 97655 non-null  int64
 39  is_driver_seat_height_adjustable  97655 non-null  int64
 40  is_day_night_rear_view_mirror     97655 non-null  int64
 41  is_ecw                            97655 non-null  int64
 42  is_speed_alert                    97655 non-null  int64
 43  ncap_rating                       97655 non-null  int64
 44  is_claim                          58592 non-null  float64
 45  torque_Nm                         97655 non-null  float64
 46  torque_rpm                        97655 non-null  float64
 47  power_bhp                         97655 non-null  float64
 48  power_rpm                         97655 non-null  float64
 49  torque_113Nm@4400rpm              97655 non-null  uint8
 50  torque_170Nm@4000rpm              97655 non-null  uint8
 51  torque_200Nm@1750rpm              97655 non-null  uint8
 52  torque_200Nm@3000rpm              97655 non-null  uint8
 53  torque_250Nm@2750rpm              97655 non-null  uint8
 54  torque_60Nm@3500rpm               97655 non-null  uint8
 55  torque_82.1Nm@3400rpm             97655 non-null  uint8
 56  torque_85Nm@3000rpm               97655 non-null  uint8
 57  torque_91Nm@4250rpm               97655 non-null  uint8
 58  power_113.45bhp@4000rpm           97655 non-null  uint8
 59  power_118.36bhp@5500rpm           97655 non-null  uint8
 60  power_40.36bhp@6000rpm            97655 non-null  uint8
 61  power_55.92bhp@5300rpm            97655 non-null  uint8
 62  power_61.68bhp@6000rpm            97655 non-null  uint8
 63  power_67.06bhp@5500rpm            97655 non-null  uint8
 64  power_88.50bhp@6000rpm            97655 non-null  uint8
 65  power_88.77bhp@4000rpm            97655 non-null  uint8
 66  power_97.89bhp@3600rpm            97655 non-null  uint8
 67  fuel_type_CNG                     97655 non-null  uint8
 68  fuel_type_Diesel                  97655 non-null  uint8
 69  fuel_type_Petrol                  97655 non-null  uint8
 70  rear_brakes_Disc                  97655 non-null  uint8
 71  rear_brakes_Drum                  97655 non-null  uint8
 72  transmission_type_Automatic       97655 non-null  uint8
 73  transmission_type_Manual          97655 non-null  uint8
 74  segment_A                         97655 non-null  uint8
 75  segment_B1                        97655 non-null  uint8
 76  segment_B2                        97655 non-null  uint8
 77  segment_C1                        97655 non-null  uint8
 78  segment_C2                        97655 non-null  uint8
 79  segment_Utility                   97655 non-null  uint8
 80  fuel_type_CNG                     97655 non-null  uint8
 81  fuel_type_Diesel                  97655 non-null  uint8
 82  fuel_type_Petrol                  97655 non-null  uint8
 83  rear_brakes_Disc                  97655 non-null  uint8
 84  rear_brakes_Drum                  97655 non-null  uint8
 85  transmission_type_Automatic       97655 non-null  uint8
 86  transmission_type_Manual          97655 non-null  uint8
 87  segment_A                         97655 non-null  uint8
 88  segment_B1                        97655 non-null  uint8
 89  segment_B2                        97655 non-null  uint8
 90  segment_C1                        97655 non-null  uint8
 91  segment_C2                        97655 non-null  uint8
 92  segment_Utility                   97655 non-null  uint8
 93  steering_type_Electric            97655 non-null  uint8
 94  steering_type_Manual              97655 non-null  uint8
 95  steering_type_Power               97655 non-null  uint8
dtypes: float64(9), int64(29), object(11), uint8(47)
memory usage: 40.9+ MB

In [38]:
data.dropna(inplace=True)
# data.drop(columns=['index', 'Unnamed: 0'], axis = 1,inplace=True)
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 58592 entries, 0 to 58591
Data columns (total 96 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Unnamed: 0                        58592 non-null  int64
 1   policy_id                         58592 non-null  object
 2   policy_tenure                     58592 non-null  float64
 3   age_of_car                        58592 non-null  float64
 4   age_of_policyholder               58592 non-null  float64
 5   area_cluster                      58592 non-null  object
 6   population_density                58592 non-null  int64
 7   make                              58592 non-null  int64
 8   segment                           58592 non-null  object
 9   model                             58592 non-null  object
 10  fuel_type                         58592 non-null  object
 11  max_torque                        58592 non-null  object
 12  max_power                         58592 non-null  object
 13  engine_type                       58592 non-null  object
 14  airbags                           58592 non-null  int64
 15  is_esc                            58592 non-null  int64
 16  is_adjustable_steering            58592 non-null  int64
 17  is_tpms                           58592 non-null  int64
 18  is_parking_sensors                58592 non-null  int64
 19  is_parking_camera                 58592 non-null  int64
 20  rear_brakes_type                  58592 non-null  object
 21  displacement                      58592 non-null  int64
 22  cylinder                          58592 non-null  int64
 23  transmission_type                 58592 non-null  object
 24  gear_box                          58592 non-null  int64
 25  steering_type                     58592 non-null  object
 26  turning_radius                    58592 non-null  float64
 27  length                            58592 non-null  int64
 28  width                             58592 non-null  int64
 29  height                            58592 non-null  int64
 30  gross_weight                      58592 non-null  int64
 31  is_front_fog_lights               58592 non-null  int64
 32  is_rear_window_wiper              58592 non-null  int64
 33  is_rear_window_washer             58592 non-null  int64
 34  is_rear_window_defogger           58592 non-null  int64
 35  is_brake_assist                   58592 non-null  int64
 36  is_power_door_locks               58592 non-null  int64
 37  is_central_locking                58592 non-null  int64
 38  is_power_steering                 58592 non-null  int64
 39  is_driver_seat_height_adjustable  58592 non-null  int64
 40  is_day_night_rear_view_mirror     58592 non-null  int64
 41  is_ecw                            58592 non-null  int64
 42  is_speed_alert                    58592 non-null  int64
 43  ncap_rating                       58592 non-null  int64
 44  is_claim                          58592 non-null  float64
 45  torque_Nm                         58592 non-null  float64
 46  torque_rpm                        58592 non-null  float64
 47  power_bhp                         58592 non-null  float64
 48  power_rpm                         58592 non-null  float64
 49  torque_113Nm@4400rpm              58592 non-null  uint8
 50  torque_170Nm@4000rpm              58592 non-null  uint8
 51  torque_200Nm@1750rpm              58592 non-null  uint8
 52  torque_200Nm@3000rpm              58592 non-null  uint8
 53  torque_250Nm@2750rpm              58592 non-null  uint8
 54  torque_60Nm@3500rpm               58592 non-null  uint8
 55  torque_82.1Nm@3400rpm             58592 non-null  uint8
 56  torque_85Nm@3000rpm               58592 non-null  uint8
 57  torque_91Nm@4250rpm               58592 non-null  uint8
 58  power_113.45bhp@4000rpm           58592 non-null  uint8
 59  power_118.36bhp@5500rpm           58592 non-null  uint8
 60  power_40.36bhp@6000rpm            58592 non-null  uint8
 61  power_55.92bhp@5300rpm            58592 non-null  uint8
 62  power_61.68bhp@6000rpm            58592 non-null  uint8
 63  power_67.06bhp@5500rpm            58592 non-null  uint8
 64  power_88.50bhp@6000rpm            58592 non-null  uint8
 65  power_88.77bhp@4000rpm            58592 non-null  uint8
 66  power_97.89bhp@3600rpm            58592 non-null  uint8
 67  fuel_type_CNG                     58592 non-null  uint8
 68  fuel_type_Diesel                  58592 non-null  uint8
 69  fuel_type_Petrol                  58592 non-null  uint8
 70  rear_brakes_Disc                  58592 non-null  uint8
 71  rear_brakes_Drum                  58592 non-null  uint8
 72  transmission_type_Automatic       58592 non-null  uint8
 73  transmission_type_Manual          58592 non-null  uint8
 74  segment_A                         58592 non-null  uint8
 75  segment_B1                        58592 non-null  uint8
 76  segment_B2                        58592 non-null  uint8
 77  segment_C1                        58592 non-null  uint8
 78  segment_C2                        58592 non-null  uint8
 79  segment_Utility                   58592 non-null  uint8
 80  fuel_type_CNG                     58592 non-null  uint8
 81  fuel_type_Diesel                  58592 non-null  uint8
 82  fuel_type_Petrol                  58592 non-null  uint8
 83  rear_brakes_Disc                  58592 non-null  uint8
 84  rear_brakes_Drum                  58592 non-null  uint8
 85  transmission_type_Automatic       58592 non-null  uint8
 86  transmission_type_Manual          58592 non-null  uint8
 87  segment_A                         58592 non-null  uint8
 88  segment_B1                        58592 non-null  uint8
 89  segment_B2                        58592 non-null  uint8
 90  segment_C1                        58592 non-null  uint8
 91  segment_C2                        58592 non-null  uint8
 92  segment_Utility                   58592 non-null  uint8
 93  steering_type_Electric            58592 non-null  uint8
 94  steering_type_Manual              58592 non-null  uint8
 95  steering_type_Power               58592 non-null  uint8
dtypes: float64(9), int64(29), object(11), uint8(47)
memory usage: 25.0+ MB

In [42]:
# Create a list of all possible variables 
list_elements = data.columns.values.tolist()
list_elements.remove('is_claim')
list_elements.remove('segment')
list_elements.remove('model')
list_elements.remove('fuel_type')
list_elements.remove('max_torque')
list_elements.remove('max_power')
list_elements.remove('engine_type')
list_elements.remove('rear_brakes_type')
list_elements.remove('steering_type')
list_elements.remove('policy_id')
list_elements.remove('Unnamed: 0')
list_elements.remove('transmission_type')
list_elements

['policy_tenure',
 'age_of_car',
 'age_of_policyholder',
 'area_cluster',
 'population_density',
 'make',
 'airbags',
 'is_esc',
 'is_adjustable_steering',
 'is_tpms',
 'is_parking_sensors',
 'is_parking_camera',
 'displacement',
 'cylinder',
 'gear_box',
 'turning_radius',
 'length',
 'width',
 'height',
 'gross_weight',
 'is_front_fog_lights',
 'is_rear_window_wiper',
 'is_rear_window_washer',
 'is_rear_window_defogger',
 'is_brake_assist',
 'is_power_door_locks',
 'is_central_locking',
 'is_power_steering',
 'is_driver_seat_height_adjustable',
 'is_day_night_rear_view_mirror',
 'is_ecw',
 'is_speed_alert',
 'ncap_rating',
 'torque_Nm',
 'torque_rpm',
 'power_bhp',
 'power_rpm',
 'torque_113Nm@4400rpm',
 'torque_170Nm@4000rpm',
 'torque_200Nm@1750rpm',
 'torque_200Nm@3000rpm',
 'torque_250Nm@2750rpm',
 'torque_60Nm@3500rpm',
 'torque_82.1Nm@3400rpm',
 'torque_85Nm@3000rpm',
 'torque_91Nm@4250rpm',
 'power_113.45bhp@4000rpm',
 'power_118.36bhp@5500rpm',
 'power_40.36bhp@6000rpm',
 'power_55.92bhp@5300rpm',
 'power_61.68bhp@6000rpm',
 'power_67.06bhp@5500rpm',
 'power_88.50bhp@6000rpm',
 'power_88.77bhp@4000rpm',
 'power_97.89bhp@3600rpm',
 'fuel_type_CNG',
 'fuel_type_Diesel',
 'fuel_type_Petrol',
 'rear_brakes_Disc',
 'rear_brakes_Drum',
 'transmission_type_Automatic',
 'transmission_type_Manual',
 'segment_A',
 'segment_B1',
 'segment_B2',
 'segment_C1',
 'segment_C2',
 'segment_Utility',
 'fuel_type_CNG',
 'fuel_type_Diesel',
 'fuel_type_Petrol',
 'rear_brakes_Disc',
 'rear_brakes_Drum',
 'transmission_type_Automatic',
 'transmission_type_Manual',
 'segment_A',
 'segment_B1',
 'segment_B2',
 'segment_C1',
 'segment_C2',
 'segment_Utility',
 'steering_type_Electric',
 'steering_type_Manual',
 'steering_type_Power']

In [45]:
import warnings
from sklearn.exceptions import DataConversionWarning


def best_linear():

    # Ignore the DataConversionWarning
    warnings.filterwarnings("ignore", category=DataConversionWarning)

    kept_2 = 10
    kept_i_2 = 0
    max = 0

    list_elements2 = list_elements.copy()
    list_of_elements = []

    while True:
        # Check which is the next best element to add 
        for i in list_elements2:
            temp = list_of_elements.copy()
            temp.append(i)
            
            def regression_f(input, price):
                model = linear_model.LogisticRegression()
                return -1*cross_val_score(model, input, price, scoring='neg_mean_squared_error', cv=10).mean()
            test_error = regression_f(data[temp], data[['is_claim']])

            if test_error < kept_2:
                kept_2 = test_error
                kept_i_2 = i 

        # stop adding elements when the error is not better than previosly obtained
        if kept_i_2 not in list_elements2:
            break

        list_of_elements.append(kept_i_2)
        list_elements2.remove(kept_i_2)

    return kept_2, list_of_elements

In [46]:
m,n = best_linear()
print(f'Linear model has error {m}, with corresponding variables {n}')

Linear model has error 0.06396777630400882, with corresponding variables ['policy_tenure']